language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install: npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master